[tool.poetry]
name = "four_p"
version = "0.1.0"
description = ""
authors = ["ali-talebi"]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
Django = "^6.1.1"
djangorestframework = "^3.18.1"
django-smart-selects = "^1.7.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
