# Generated by Django 6.1.1 on 2026-10-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=50, verbose_name='فامیلی')),
                ('code_melli', models.CharField(max_length=11, unique=True, verbose_name='کد ملی')),
            ],
            options={
                'verbose_name_plural': 'افراد',
                'db_table': 'person_table',
            },
        ),
    ]
