# Generated by Django 6.1.1 on 2026-10-06 19:23

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0001_initial'),
        ('person_grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person_grade_p_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person_grade.person', verbose_name='فرد')),
                ('model_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_one.p1_methods', verbose_name='روش گریدینگ')),
            ],
            options={
                'verbose_name': 'گریدینگ شغلی فرد',
                'verbose_name_plural': 'گریدینگ شغلی افراد',
                'db_table': 'person_grade_p_one_table',
            },
        ),
        migrations.CreateModel(
            name='PersonFactorSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amel', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='model_head', chained_model_field='model_head', on_delete=django.db.models.deletion.PROTECT, to='p_one.avamel', verbose_name='عامل')),
                ('complexity', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='amel', chained_model_field='amel', on_delete=django.db.models.deletion.PROTECT, to='p_one.complexity', verbose_name='پیچیدگی')),
                ('frequency', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='model_head', chained_model_field='model_head', on_delete=django.db.models.deletion.PROTECT, to='p_one.frequnecy', verbose_name='فراوانی')),
                ('model_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_one.p1_methods', verbose_name='روش گریدینگ')),
                ('periority', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='model_head', chained_model_field='model_head', on_delete=django.db.models.deletion.PROTECT, to='p_one.periority', verbose_name='اهمیت')),
                ('person_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_selections', to='person_grade.person_grade_p_one', verbose_name='گریدینگ فرد')),
            ],
        ),
    ]
