# Generated by Django 6.1.1 on 2026-10-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_grade', '0002_person_grade_p_one_personfactorselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_Grading_Arzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masir_shoghli', models.PositiveSmallIntegerField(verbose_name='مسیر شغلی')),
                ('grade_shoghli', models.PositiveSmallIntegerField(verbose_name='گرید شغلی')),
                ('min_score', models.PositiveSmallIntegerField(verbose_name='min')),
                ('mid_score', models.PositiveSmallIntegerField(verbose_name='mid')),
                ('max_score', models.PositiveSmallIntegerField(verbose_name='max')),
            ],
            options={
                'verbose_name_plural': 'امتیازات گردینگ عرضی',
                'db_table': 'grade_arzi_table',
            },
        ),
        migrations.AlterModelOptions(
            name='personfactorselection',
            options={'verbose_name_plural': 'امتیاز دهی به عوامل'},
        ),
    ]
