# Generated by Django 6.1.1 on 2026-09-12 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avamel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amel_name', models.CharField(max_length=50, verbose_name='نام عامل')),
            ],
            options={
                'verbose_name_plural': 'عوامل در روشهای ارزشیابی',
                'db_table': 'table_avamels',
            },
        ),
        migrations.CreateModel(
            name='p1_methods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=20, verbose_name='نام روش')),
            ],
            options={
                'verbose_name_plural': 'نام روشها در گردینگ شغلی',
                'db_table': 'table_p1_method',
            },
        ),
        migrations.CreateModel(
            name='amel_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام  سطح امتیاز')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('complexity', models.SmallIntegerField(verbose_name='\u200dپیچیدگی')),
                ('frequency', models.SmallIntegerField(verbose_name='فراوانی')),
                ('score', models.IntegerField(verbose_name='امتیاز')),
                ('amel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='p_one.avamel', verbose_name='عامل')),
            ],
            options={
                'verbose_name_plural': 'امتیازدهی به عوامل',
                'db_table': 'table_amel_score',
            },
        ),
        migrations.AddField(
            model_name='avamel',
            name='model_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avamels', to='p_one.p1_methods', verbose_name='مدل ارزشیابی'),
        ),
    ]
