# Generated by Django 6.1.1 on 2026-10-02 11:20

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p1_methods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=20, verbose_name='نام روش')),
                ('score', models.IntegerField(verbose_name='مجموع امتیاز')),
                ('dimentions', models.CharField(choices=[('2D', '2D'), ('3D', '3D')], max_length=10, null=True, verbose_name='ابعاد این روش')),
                ('complexity_level', models.IntegerField(verbose_name='تعداد سطوح پیچیدگی')),
                ('frequency_level', models.IntegerField(verbose_name='تعداد سظوح فراوانی')),
                ('importance_level', models.IntegerField(verbose_name='تعداد سطوح اهمیت')),
            ],
            options={
                'verbose_name_plural': 'نام روشها در گردینگ شغلی',
                'db_table': 'table_p1_method',
            },
        ),
        migrations.CreateModel(
            name='TableGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_key', models.CharField(choices=[('complexity', 'جدول سطوح پیچیدگی'), ('periority', 'جدول سطوح اهمیت'), ('frequency', 'جدول سطوح فراوانی'), ('avamel', 'جدول عوامل ارزیابی'), ('methods', 'جدول روش\u200cهای ارزیابی')], max_length=50, unique=True, verbose_name='شناسه جدول')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فارسی جدول')),
                ('description', models.TextField(verbose_name='توضیحات و تعریف کلی جدول')),
            ],
            options={
                'verbose_name': 'راهنمای جدول',
                'verbose_name_plural': 'راهنمای جداول',
                'db_table': 'table_guide',
            },
        ),
        migrations.CreateModel(
            name='Frequnecy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_name', models.CharField(max_length=50, verbose_name='نام سطح فراوانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('definition', models.TextField(verbose_name='توضیحات')),
                ('model_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='p_one.p1_methods', verbose_name='مدل ارزشیابی')),
                ('table_guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_one.tableguide', verbose_name='توضیح جدول')),
            ],
            options={
                'verbose_name_plural': 'فراوانی',
                'db_table': 'table_frequency',
            },
        ),
        migrations.CreateModel(
            name='avamel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amel_name', models.CharField(max_length=200, verbose_name='نام عامل')),
                ('self_score', models.IntegerField(verbose_name='امتیاز این عامل')),
                ('definition', models.TextField(verbose_name='تعریف عامل')),
                ('model_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avamels', to='p_one.p1_methods', verbose_name='مدل ارزشیابی')),
            ],
            options={
                'verbose_name_plural': 'عوامل در روشهای ارزشیابی',
                'db_table': 'table_avamels',
            },
        ),
        migrations.CreateModel(
            name='Periority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periority_name', models.CharField(verbose_name='نام سطح اهمیت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('definition', models.TextField(verbose_name='توضیحات')),
                ('model_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periorites', to='p_one.p1_methods', verbose_name='مدل ارزشیابی')),
                ('table_guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_one.tableguide', verbose_name='توضیح جدول')),
            ],
            options={
                'verbose_name_plural': 'اهمیت',
                'db_table': 'table_periority',
            },
        ),
        migrations.CreateModel(
            name='amel_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام سطح امتیاز')),
                ('score', models.IntegerField(verbose_name='امتیاز')),
                ('amel', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='model_head', chained_model_field='model_head', on_delete=django.db.models.deletion.PROTECT, related_name='amel_scores', to='p_one.avamel', verbose_name='عامل')),
                ('complexity', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='amel', chained_model_field='amel', on_delete=django.db.models.deletion.PROTECT, related_name='complexities_scores', to='p_one.avamel', verbose_name='پیچیدگی')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_one.frequnecy', verbose_name='سطح فراوانی')),
                ('model_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_one.p1_methods', verbose_name='روش ارزشیابی')),
                ('periority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_one.periority', verbose_name='سطح اهمیت')),
            ],
            options={
                'verbose_name_plural': 'امتیازدهی به عوامل',
                'db_table': 'table_amel_score',
            },
        ),
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_name', models.CharField(max_length=50, verbose_name='نام سطح پیچیدگی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('definition', models.TextField(verbose_name='توضیحات')),
                ('amel', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='model_head', chained_model_field='model_head', on_delete=django.db.models.deletion.PROTECT, to='p_one.avamel', verbose_name='عامل')),
                ('model_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_one.p1_methods', verbose_name='مدل ارزشیابی')),
                ('table_guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_one.tableguide', verbose_name='توضیح جدول')),
            ],
            options={
                'verbose_name_plural': 'پیچیدگی',
                'db_table': 'table_complexity',
            },
        ),
    ]
