# Generated by Django 6.1.1 on 2026-10-02 11:43

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amel_score',
            name='complexity',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='amel', chained_model_field='amel', on_delete=django.db.models.deletion.PROTECT, related_name='complexities_scores', to='p_one.complexity', verbose_name='پیچیدگی'),
        ),
    ]
