# Generated by Django 6.1.1 on 2026-09-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p1_methods',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='مجموع امتیاز'),
        ),
    ]
