# Generated by Django 6.1.1 on 2026-09-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0002_p1_methods_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='avamel',
            name='self_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='امتیاز این عامل'),
        ),
    ]
