# Generated by Django 6.1.1 on 2026-10-02 13:41

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0002_alter_amel_score_complexity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amel_score',
            name='name',
        ),
        migrations.AddField(
            model_name='complexity',
            name='short_definition',
            field=models.CharField(max_length=250, null=True, verbose_name='تعریف کوتاه'),
        ),
        migrations.AlterField(
            model_name='amel_score',
            name='complexity',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='amel', chained_model_field='amel', on_delete=django.db.models.deletion.PROTECT, related_name='complexities_scores', to='p_one.complexity', verbose_name='سطح پیچیدگی'),
        ),
        migrations.AlterField(
            model_name='complexity',
            name='complexity_name',
            field=models.CharField(max_length=50, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='complexity',
            name='definition',
            field=models.TextField(verbose_name='تعریف بلند'),
        ),
        migrations.AlterField(
            model_name='complexity',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
