# Generated by Django 6.1.1 on 2026-09-24 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0003_avamel_self_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_name', models.CharField(max_length=50, verbose_name='نام سطح پیچیدگی')),
                ('complexity_description', models.TextField(verbose_name='توضیحات')),
                ('amel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexities', to='p_one.avamel')),
            ],
            options={
                'db_table': 'table_complexity',
            },
        ),
        migrations.CreateModel(
            name='Frequnecy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_name', models.CharField(max_length=50, verbose_name='نام سطح فراوانی')),
                ('frequency_description', models.TextField(verbose_name='توضیحات')),
                ('amel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='p_one.avamel')),
            ],
            options={
                'db_table': 'table_frequency',
            },
        ),
        migrations.CreateModel(
            name='Periority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periority_name', models.CharField(verbose_name='نام سطح اهمیت')),
                ('periority_description', models.TextField(verbose_name='توضیحات')),
                ('amel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periorites', to='p_one.avamel')),
            ],
            options={
                'db_table': 'table_periority',
            },
        ),
    ]
