# Generated by Django 6.1.1 on 2026-10-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0003_remove_amel_score_name_complexity_short_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amel_score',
            name='score',
            field=models.PositiveIntegerField(verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='avamel',
            name='self_score',
            field=models.PositiveIntegerField(verbose_name='امتیاز این عامل'),
        ),
        migrations.AlterField(
            model_name='frequnecy',
            name='definition',
            field=models.TextField(verbose_name='تعریف'),
        ),
        migrations.AlterField(
            model_name='p1_methods',
            name='complexity_level',
            field=models.PositiveIntegerField(verbose_name='تعداد سطوح پیچیدگی'),
        ),
        migrations.AlterField(
            model_name='p1_methods',
            name='frequency_level',
            field=models.PositiveIntegerField(verbose_name='تعداد سظوح فراوانی'),
        ),
        migrations.AlterField(
            model_name='p1_methods',
            name='importance_level',
            field=models.PositiveIntegerField(verbose_name='تعداد سطوح اهمیت'),
        ),
        migrations.AlterField(
            model_name='periority',
            name='definition',
            field=models.TextField(verbose_name='تعریف'),
        ),
    ]
