# Generated by Django 6.1.1 on 2026-09-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0004_complexity_frequnecy_periority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complexity',
            options={'verbose_name_plural': 'پیچیدگی'},
        ),
        migrations.AlterModelOptions(
            name='frequnecy',
            options={'verbose_name_plural': 'فراوانی'},
        ),
        migrations.AlterModelOptions(
            name='periority',
            options={'verbose_name_plural': 'اهمیت'},
        ),
        migrations.AddField(
            model_name='amel_score',
            name='periority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='p_one.periority', verbose_name='اهمیت'),
        ),
        migrations.AlterField(
            model_name='amel_score',
            name='complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='p_one.complexity', verbose_name='پیچیدگی'),
        ),
        migrations.AlterField(
            model_name='amel_score',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='amel_score',
            name='frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='p_one.frequnecy', verbose_name='فراوانی'),
        ),
        migrations.AlterField(
            model_name='amel_score',
            name='name',
            field=models.CharField(max_length=20, verbose_name='نام سطح امتیاز'),
        ),
    ]
