# Generated by Django 6.1.1 on 2026-10-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0004_alter_amel_score_score_alter_avamel_self_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amel_score',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='avamel',
            name='self_score',
            field=models.PositiveSmallIntegerField(verbose_name='امتیاز این عامل'),
        ),
        migrations.AlterField(
            model_name='p1_methods',
            name='complexity_level',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد سطوح پیچیدگی'),
        ),
        migrations.AlterField(
            model_name='p1_methods',
            name='frequency_level',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد سظوح فراوانی'),
        ),
        migrations.AlterField(
            model_name='p1_methods',
            name='importance_level',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد سطوح اهمیت'),
        ),
    ]
