# Generated by Django 6.1.1 on 2026-09-24 09:16

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0005_alter_complexity_options_alter_frequnecy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amel_score',
            name='complexity',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='amel', chained_model_field='amel', on_delete=django.db.models.deletion.PROTECT, to='p_one.complexity', verbose_name='پیچیدگی'),
        ),
        migrations.AlterField(
            model_name='amel_score',
            name='frequency',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='amel', chained_model_field='amel', on_delete=django.db.models.deletion.PROTECT, to='p_one.frequnecy', verbose_name='فراوانی'),
        ),
        migrations.AlterField(
            model_name='amel_score',
            name='periority',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='amel', chained_model_field='amel', null=True, on_delete=django.db.models.deletion.PROTECT, to='p_one.periority', verbose_name='اهمیت'),
        ),
    ]
