# Generated by Django 6.1.1 on 2026-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0006_alter_amel_score_complexity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avamel',
            name='amel_name',
            field=models.CharField(max_length=200, verbose_name='نام عامل'),
        ),
    ]
