# Generated by Django 6.1.1 on 2026-09-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_one', '0007_alter_avamel_amel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='p1_methods',
            name='dimentions',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], max_length=10, null=True, verbose_name='ابعاد این روش'),
        ),
    ]
